name: rental
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^5.0.3
  path: ^1.8.2
  intl: ^0.17.0
  shimmer: ^2.0.0
  jwt_decoder: ^2.0.1
  event_bus: ^2.0.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.4
  flutter_cache_manager: ^3.3.0
  sprintf: ^7.0.0
  permission_handler: ^10.2.0
  get_storage: ^2.1.1
  dots_indicator: ^2.1.0
  flutter_staggered_grid_view: ^0.6.2
  dropdown_button2: ^2.0.0
  #Gallery
  image_cropper: ^3.0.1
  photo_view: ^0.14.0
  photo_manager: 2.5.2
  path_provider: ^2.0.13
  camera: ^0.10.3+2
  flutter_image_compress: ^1.1.3
  flutter_rating_bar: ^4.0.1
  path_drawing: ^1.0.1
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 180 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true

  colors:
    inputs:
      - assets/color/colors.xml
#flutter packages pub run build_runner build

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/